### ISSUE TITLE
Doesn't seem to install on Xcode 6.3.2 on Yosemite with Alcatraz

### ISSUE THREAD

**Issue by Shadester** [lechium/ProvisioningProfileCleaner#1]

**Comment by guillaumealgis** [comment]
This is due to the fact that Alcatraz is looking for a `xcodeproj` file with the exact same name as the plugin when building.

In this case, the plugin is named `XCProfileCleaner` and the xcodeproj `ProvisioningProfileCleaner.xcodeproj`.
So either rename the plugin with a PR on [alcatraz-packages](https://github.com/supermarin/alcatraz-packages), or rename the xcodeproj to `XCProfileCleaner.xcodeproj`.

**Comment by jurre** [comment]
I've renamed the package on alcatraz, feel free to rename it here and on alcatraz if you prefer the old name :)
